<a href="https://colab.research.google.com/github/Sarfaraz021/Deep-Learning/blob/main/DL_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tensorflow import keras
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Excel Data files/data.csv')
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [4]:
X_train, X_test, y_train, y_test = train_test_split(df[['age','affordibility']], df.bought_insurance, test_size = 0.2, random_state = 25)

In [5]:
X_train_scaled = X_train.copy()
X_train_scaled ['age']= (X_train_scaled['age']/100)

X_test_scaled = X_test.copy()
X_test_scaled ['age']= (X_test_scaled['age']/100)



In [6]:
model = keras.Sequential([
    keras.layers.Dense(1,input_shape = (2,), activation = 'sigmoid', kernel_initializer = 'ones', bias_initializer = 'zeros')
])

model.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
)

In [10]:
model.fit(X_train_scaled, y_train, epochs = 5000)

Streaming output truncated to the last 5000 lines.
Epoch 2016/5000
1/1 [==============================] - 0s 49ms/step - loss: 0.4980 - accuracy: 0.9091
Epoch 2017/5000
1/1 [==============================] - 0s 48ms/step - loss: 0.4980 - accuracy: 0.9091
Epoch 2018/5000
1/1 [==============================] - 0s 53ms/step - loss: 0.4980 - accuracy: 0.9091
Epoch 2019/5000
1/1 [==============================] - 0s 47ms/step - loss: 0.4980 - accuracy: 0.9091
Epoch 2020/5000
1/1 [==============================] - 0s 58ms/step - loss: 0.4979 - accuracy: 0.9091
Epoch 2021/5000
1/1 [==============================] - 0s 46ms/step - loss: 0.4979 - accuracy: 0.9091
Epoch 2022/5000
1/1 [==============================] - 0s 42ms/step - loss: 0.4979 - accuracy: 0.9091
Epoch 2023/5000
1/1 [==============================] - 0s 70ms/step - loss: 0.4978 - accuracy: 0.9091
Epoch 2024/5000
1/1 [==============================] - 0s 44ms/step - loss: 0.4978 - accuracy: 0.9091
Epoch 2025/5000
1/1 [==========

In [12]:
model.evaluate(X_test_scaled, y_test)

1/1 [==============================] - 0s 31ms/step - loss: 0.3025 - accuracy: 1.0000


[0.3025059700012207, 1.0]

In [13]:
X_test_scaled

age  affordibility
2   0.47              1
10  0.18              1
21  0.26              0
11  0.28              1
14  0.49              1
9   0.61              1

In [15]:
model.predict(X_test_scaled)

1/1 [==============================] - 0s 48ms/step


array([[0.72434247],
       [0.291342  ],
       [0.12941581],
       [0.43801376],
       [0.74914074],
       [0.86548483]], dtype=float32)

In [16]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [18]:
coef, intercept = model.get_weights()
coef, intercept

(array([[6.396484 ],
        [1.5289772]], dtype=float32),
 array([-3.5692196], dtype=float32))

# Making the same neural network from scratch using python

In [25]:
def sigmoid(x):
  import math
  return (1/(1+math.exp(-x)))

def prediction_function(age, affordibility):
  weighted_sum = (coef[0]*age) + (coef[1]*affordibility) + intercept
  return sigmoid(weighted_sum)


In [26]:
prediction_function(.18,1)


0.2913419916885238

In [27]:
prediction_function(.47,1)

0.7243424581774252